import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import InputField from './components/inputField'
import { useState } from 'react'

export default function Home() {
  const [inputValue, setInputValue] = useState('')

  const handleInputChange = (event: any) => {
    setInputValue(event.target.value)
  }
  return (
    <>
      <Head>
        <title>MindSift</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.inputWrapper}>
          <InputField label='What&apos;s on your mind ?' value={inputValue} onChange={handleInputChange}></InputField>
        </div>
      </main>
    </>
  )
}