import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import InputField from '../pages/components/InputField'
import { useState } from 'react'

export default function Home() {
  const [inputValue, setInputValue] = useState('')

  const handleInputValue = (e: any) => {
    setInputValue(e.target.value)
  }
  return (
    <>
      <Head>
        <title>MindSift</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.title}>MindSift</div>
      <InputField label='What&apos;s on your mind ?' value={inputValue} onChange={handleInputValue}></InputField>
    </>
  )
}